/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OntologyRouteImport } from './routes/ontology'
import { Route as ExtractionsRouteImport } from './routes/extractions'
import { Route as IndexRouteImport } from './routes/index'

const OntologyRoute = OntologyRouteImport.update({
  id: '/ontology',
  path: '/ontology',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractionsRoute = ExtractionsRouteImport.update({
  id: '/extractions',
  path: '/extractions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/extractions': typeof ExtractionsRoute
  '/ontology': typeof OntologyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/extractions': typeof ExtractionsRoute
  '/ontology': typeof OntologyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/extractions': typeof ExtractionsRoute
  '/ontology': typeof OntologyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/extractions' | '/ontology'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/extractions' | '/ontology'
  id: '__root__' | '/' | '/extractions' | '/ontology'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExtractionsRoute: typeof ExtractionsRoute
  OntologyRoute: typeof OntologyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ontology': {
      id: '/ontology'
      path: '/ontology'
      fullPath: '/ontology'
      preLoaderRoute: typeof OntologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extractions': {
      id: '/extractions'
      path: '/extractions'
      fullPath: '/extractions'
      preLoaderRoute: typeof ExtractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExtractionsRoute: ExtractionsRoute,
  OntologyRoute: OntologyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
